kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ldap-group-syncer
rules:
  - verbs:
      - get
      - list
      - create
      - update
      - patch
    apiGroups:
      - ''
      - user.openshift.io
    resources:
      - groups
