apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
    - mappingMethod: add
      name: EntraID
      openID:
        claims:
          email:
            - email
          name:
            - name
          preferredUsername:
            - email
        clientID: 3512bf63-d2d3-41c4-b8f9-df3fe11439ac
        clientSecret:
          name: entraid-oidc
        extraScopes: []
        issuer: 'https://login.microsoftonline.com/e95f1b23-abaf-45ee-821d-b7ab251ab3bf/v2.0'
      type: OpenID
    - mappingMethod: add
      name: IAM
      openID:
        ca:
          name: openid-ca
        claims:
          email:
            - email
          name:
            - name
          preferredUsername:
            - email
        clientID: piv
        clientSecret:
          name: openid-client-secret-piv
        extraScopes: []
        issuer: 'https://keycloak-sso-aws.apps.vapo.va.gov/auth/realms/iam'
      type: OpenID
  
