kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: vapo-project-request
  namespace: openshift-config
objects:
  - apiVersion: project.openshift.io/v1
    kind: Project
    metadata:
      annotations:
        openshift.io/description: '${PROJECT_DESCRIPTION}'
        openshift.io/display-name: '${PROJECT_DISPLAYNAME}'
        openshift.io/requester: '${PROJECT_REQUESTING_USER}'
      labels:
        cpu: 2cpu
        mem: 4gi
        storagesize: 20gstorage
      name: '${PROJECT_NAME}'
    spec: {}
    status: {}
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: admin
      namespace: '${PROJECT_NAME}'
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: admin
    subjects:
      - apiGroup: rbac.authorization.k8s.io
        kind: User
        name: '${PROJECT_ADMIN_USER}'
  - apiVersion: v1
    kind: ResourceQuota
    metadata:
      name: '${PROJECT_NAME}-quota'
    spec:
      hard:
        configmaps: '100'
        replicationcontrollers: '20'
        secrets: '100'
        services: '100'
        services.loadbalancers: '2'
  - apiVersion: v1
    kind: LimitRange
    metadata:
      name: '${PROJECT_NAME}-limit-range'
    spec:
      limits:
        - default:
            cpu: 200m
            memory: 200Mi
          defaultRequest:
            cpu: 100m
            memory: 100Mi
          type: Container
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-from-same-namespace
    spec:
      ingress:
        - from:
            - podSelector: {}
      podSelector: {}
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-from-openshift-ingress
    spec:
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  network.openshift.io/policy-group: ingress
      podSelector: {}
      policyTypes:
        - Ingress
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-from-openshift-devspaces
    spec:
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  kubernetes.io/metadata.name: openshift-devspaces
      podSelector: {}
      policyTypes:
        - Ingress
  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: allow-from-openshift-monitoring
    spec:
      podSelector: {}
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  network.openshift.io/policy-group: monitoring
      policyTypes:
        - Ingress
  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: allow-from-same-namespace
    spec:
      podSelector: {}
      ingress:
        - from:
            - podSelector: {}
      policyTypes:
        - Ingress
  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: default-deny
    spec:
      podSelector: {}
      policyTypes:
        - Ingress
parameters:
  - name: PROJECT_NAME
  - name: PROJECT_DISPLAYNAME
  - name: PROJECT_DESCRIPTION
  - name: PROJECT_ADMIN_USER
  - name: PROJECT_REQUESTING_USER
