apiVersion: operator.openshift.io/v1alpha1
kind: CertManager
metadata:
  name: cluster
  namespace: cert-manager-operator
spec:
  logLevel: Normal
  managementState: Managed
  observedConfig: null
  operatorLogLevel: Normal
  unsupportedConfigOverrides: null
