kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-etcd-backup
rules:
  - verbs:
      - get
      - list
    apiGroups:
      - ''
    resources:
      - nodes
  - verbs:
      - get
      - list
      - create
      - delete
      - watch
    apiGroups:
      - ''
    resources:
      - pods
      - pods/log
